# Site settings
title: Ceci n'est pas me #'
email: erick@ceci-nest-pas.me
#description: > # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
 url: "ceci-nest-pas.me" # the base hostname & protocol for your site
twitter_username: erickomoto 
github_username:  efferifick

# Build settings
markdown: kramdown


paginate: 4
paginate_path: "blog/page:num"
